---
version: 1

build_arg_defaults:
  # EE_BASE_IMAGE: 'automationhub22-1.lab.local/ee-minimal-rhel8:latest'
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:1.0.0-395'
ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  # prepend:
  #   - RUN pip3 install --upgrade pip setuptools
  # prepend_galaxy:
  #   - ENV ANSIBLE_GALAXY_SERVER_LIST=pah_community
  #   #, rh_certified, release_galaxy
  #   - ENV ANSIBLE_GALAXY_SERVER_PAH_COMMUNITY_URL=https://aap-rhel-92-1.lab.local:444/api/galaxy/content/community/
  #   # - ENV ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_URL=https://aap-rhel-92-1.lab.local:444/api/galaxy/content/rh-certified/
  #   # - ENV ANSIBLE_GALAXY_SERVER_RELEASE_GALAXY_URL=https://galaxy.ansible.com/
  #   - ARG ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_TOKEN
  #   # - ARG ANSIBLE_GALAXY_SERVER_PAH_COMMUNITY_TOKEN
  append:
    #- RUN pip3 list installed
    - RUN microdnf install which