collections:
# - name: cisco-ios-4.2.0.tar.gz
#   version: 4.2.0
# - name: ansible-netcommon-4.1.0.tar.gz
#   version: 4.1.0
# - name: ansible-utils-2.8.0.tar.gz
#   version: 2.8.0

# from galaxy.ansible.com, no authentication required.
- name: cisco.ios
  version: 5.2.0
  source: https://galaxy.ansible.com

# - name: iamgini.demo_colelction_roles_modules

# from Private Automation Hub
- name: amazon.aws
  version: 6.5.0
  source: https://aap-rhel-92-1.lab.local:444/api/galaxy/content/rh-certified/

# from Private Automation Hub
- name: iamgini.demo_colelction_roles_modules
  version: 1.0.1
  source: https://aap-rhel-92-1.lab.local:444/api/galaxy/content/community/ 