# This is the AAP installer inventory file intended for the Container growth deployment topology.
# This inventory file expects to be run from the host where AAP will be installed.
# Please consult the Ansible Automation Platform product documentation about this topology's tested hardware configuration.
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.7/plan-ref_installation_deployment_models
#
# Please consult the docs if you're unsure what to add
# For all optional variables please consult the included README.md
# or the Ansible Automation Platform documentation:
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.7/install-con_aap_containerized_installation_intro

# This section is for your AAP Gateway host(s)
# -----------------------------------------------------
[automationgateway]
aapaio.lab.gineesh.com

# This section is for your AAP Controller host(s)
# -----------------------------------------------------
[automationcontroller]
aapaio.lab.gineesh.com

# This section is for your AAP Automation Hub host(s)
# -----------------------------------------------------
[automationhub]
aapaio.lab.gineesh.com

# This section is for your AAP EDA Controller host(s)
# -----------------------------------------------------
[automationeda]
aapaio.lab.gineesh.com

# This section is for your AAP Automation Metrics Service host(s)
# -----------------------------------------------------
[automationmetrics]
aapaio.lab.gineesh.com

# This section is for your AAP Lightspeed host(s)
# -----------------------------------------------------
# [ansiblelightspeed]
# aapaio.lab.gineesh.com

# This section is for your Ansible MCP Server host(s)
# -----------------------------------------------------
[ansiblemcp]
aapaio.lab.gineesh.com

# This section is for the AAP database
# -----------------------------------------------------
[database]
aapaio.lab.gineesh.com

[all:vars]
# Ansible
# ansible_connection=local
ansible_user=ec2-user

# For a comprehensive list of all inventory file variables, see:
# https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.7/install-assembly_appendix_inventory_file_vars

# Common variables
# -----------------------------------------------------
postgresql_admin_username=postgres
postgresql_admin_password=aapadmin

bundle_install=true
# The bundle directory must include /bundle in the path
bundle_dir='{{ lookup("ansible.builtin.env", "PWD") }}/bundle'


redis_mode=standalone

# AAP Gateway
# -----------------------------------------------------
gateway_admin_password=aapadmin
gateway_pg_host=aapaio.lab.gineesh.com
gateway_pg_password=aapadmin

# AAP Controller
# -----------------------------------------------------
controller_admin_password=aapadmin
controller_pg_host=aapaio.lab.gineesh.com
controller_pg_password=aapadmin
controller_percent_memory_capacity=0.5

# AAP Automation Hub
# -----------------------------------------------------
hub_admin_password=aapadmin
hub_pg_host=aapaio.lab.gineesh.com
hub_pg_password=aapadmin
hub_seed_collections=false

# AAP EDA Controller
# -----------------------------------------------------
eda_admin_password=aapadmin
eda_pg_host=aapaio.lab.gineesh.com
eda_pg_password=aapadmin

# AAP Automation Metrics Service
# -----------------------------------------------------
automationmetrics_pg_host=aapaio.lab.gineesh.com
automationmetrics_pg_password=aapadmin
automationmetrics_controller_read_pg_host=aapaio.lab.gineesh.com
automationmetrics_controller_read_pg_password=aapadmin

# NSIBLE_BECOME=true ansible-playbook -i inventory-growth-1 ansible.containerized_installer.install -e @feature_flags_metrics.yml

# Red Hat Ansible Lightspeed Deployment Settings
lightspeed_admin_user=admin
lightspeed_admin_password=aapadmin
lightspeed_admin_email=admin@example.com
lightspeed_pg_host=aapaio.lab.gineesh.com
lightspeed_pg_password=aapadmin

# MCP
mcp_allow_write_operations=true
mcp_ignore_certificate_errors=true