apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-aap-hub-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-rwx
  nfs:
    server: 192.168.0.175
    path: /aap-hub
