apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-aap-hub-pvc
  namespace: aap
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: efs-aap-hub-pv
  storageClassName: ""
